# Generated by Django 2.2.10 on 2021-04-13 11:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Predictions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locations', models.CharField(max_length=30)),
                ('sqft', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(250)])),
                ('bhk', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('bath', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
            ],
        ),
    ]
